version: "3.6"
services:
  devcontainer:
    image: ghcr.io/cachix/devenv:latest
    volumes:
      - ../..:/workspaces:cached
    security_opt:
      - label:disable

  frontend:
    #profiles: ["dev"]
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    stdin_open: true
    command: yarn start
    volumes:
       - /workspaces/react-codespaces:/usr/src/app
